<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Selenium.Support" Version="4.19.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\VP.Selenium.Contracts\VP.Selenium.Contracts.csproj" />
    </ItemGroup>
</Project>