<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PDFiumCore" Version="133.0.6844" />
  </ItemGroup>
</Project>